workflows:
  ios:
    name: iOS Build and Release
    max_build_duration: 60
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install  # CocoaPods 의존성 설치
          cd ..
      - name: Build iOS app
        script: |
          xcodebuild -project ios/DIMI_FRIEND.xcodeproj \
            -scheme DIMI_FRIEND \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/DIMI_FRIEND.xcarchive \
            clean archive
      - name: Deploy to App Store
        script: |
          curl -s https://raw.githubusercontent.com/codemagic-ci-cd/ios-codemagic-scripts/master/fastlane_upload_to_app_store.sh > fastlane_upload_to_app_store.sh
          chmod +x fastlane_upload_to_app_store.sh
          ./fastlane_upload_to_app_store.sh