workflows:
  react_native_ios:
    name: React Native iOS Workflow
    integrations:
      app_store_connect: DIMIFRIEND_CODEMAGIC # Codemagic에 추가한 App Store Connect API 키 이름
    environment:
      vars:
        PROJECT_NAME: "DIMI_FRIEND" # 실제 프로젝트 이름으로 변경하세요
        BUNDLE_IDENTIFIER: "com.dimifriends" # 실제 번들 식별자로 변경하세요
        APPLE_TEAM_ID: "34B6SX46T2" # Apple 개발자 팀 ID
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Set build number
        script: |
          cd ios
          agvtool new-version -all $(date +%s)
          cd ..
      - name: Build iOS
        script: |
          xcodebuild -project ios/$PROJECT_NAME.xcodeproj \
                     -scheme $PROJECT_NAME \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/$PROJECT_NAME.xcarchive \
                     clean archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/$PROJECT_NAME.xcarchive \
                     -exportOptionsPlist ios/exportOptions.plist \
                     -exportPath $PWD/build/ipa
    artifacts:
      - build/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false