workflows:
  ios:
    name: iOS Build and Release
    max_build_duration: 60
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          npx react-native run-ios --mode Release
      - name: Deploy to App Store
        script: |
          # App Store 배포 스크립트 시작
          curl -s https://raw.githubusercontent.com/codemagic-ci-cd/ios-codemagic-scripts/master/fastlane_upload_to_app_store.sh > fastlane_upload_to_app_store.sh
          chmod +x fastlane_upload_to_app_store.sh
          ./fastlane_upload_to_app_store.sh
          # App Store 배포 스크립트 끝
