workflows:
  ios:
    name: iOS Build and Release
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          xcodebuild -project ios/DIMI_FRIEND.xcodeproj \
            -scheme DIMI_FRIEND \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/DIMI_FRIEND.xcarchive \
            DEVELOPMENT_TEAM=34B6SX46T2 \
            clean archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/DIMI_FRIEND.xcarchive \
            -exportPath $PWD/build/DIMI_FRIEND \
            -exportOptionsPlist ios/exportOptions.plist
      - name: Deploy to App Store
        script: |
          curl -s https://raw.githubusercontent.com/codemagic-ci-cd/ios-codemagic-scripts/master/fastlane_upload_to_app_store.sh > fastlane_upload_to_app_store.sh
          chmod +x fastlane_upload_to_app_store.sh
          ./fastlane_upload_to_app_store.sh
