# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0'
prepare_react_native_project!

# (선택 사항) USE_FRAMEWORKS 환경변수가 없다면, 필요에 따라 use_frameworks! 설정 추가 가능
# unless ENV['USE_FRAMEWORKS']
#   use_frameworks! :linkage => :static
# end

target 'DIMI_FRIEND' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase Pods (modular_headers 옵션 제거)
  pod 'FirebaseAuth', '11.7.0'
  pod 'RecaptchaInterop'
  pod 'FirebaseFirestoreInternal'
  pod 'GoogleUtilities'
  pod 'FirebaseCore', '11.7.0'
  pod 'FirebaseCoreInternal', '11.7.0'
  pod 'FirebaseStorage', '11.7.0'
  pod 'FirebaseCoreExtension', '11.7.0'
  pod 'FirebaseAppCheckInterop', '11.9.0'
  pod 'FirebaseAuthInterop', '11.9.0'
  pod 'FirebaseMessagingInterop', '11.9.0'
  pod 'GTMSessionFetcher', '3.4.0'

  target 'DIMI_FRIENDTests' do
    inherit! :complete
  end

  post_install do |installer|
    # 모든 타겟에서 모듈 사용을 강제
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      end
    end
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end