use_modular_headers!
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '14.0'
#use_modular_headers!    # 이 줄을 추가 또는 주석 해제

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'DIMI_FRIEND' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase Pods (버전은 필요에 따라 조정)
  pod 'FirebaseAuth', '11.7.0', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true
  pod 'FirebaseFirestoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', '11.7.0', :modular_headers => true
  pod 'FirebaseCoreInternal', '11.7.0', :modular_headers => true
  pod 'FirebaseStorage', '11.7.0', :modular_headers => true
  pod 'FirebaseCoreExtension', '11.7.0', :modular_headers => true
  pod 'FirebaseAppCheckInterop', '11.9.0', :modular_headers => true
  pod 'FirebaseAuthInterop', '11.9.0', :modular_headers => true
  pod 'FirebaseMessagingInterop', '11.9.0', :modular_headers => true
  pod 'GTMSessionFetcher', '3.4.0', :modular_headers => true

  target 'DIMI_FRIENDTests' do
    inherit! :complete
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      # gRPC 관련 타겟은 모듈 정의를 끄도록 설정 (모듈맵 생성을 우회)
      if target.name.include?("gRPC")
        target.build_configurations.each do |config|
          config.build_settings['DEFINES_MODULE'] = 'NO'
        end
      end
  
      # 모든 타겟에 대해 배포 대상(iOS deployment target) 및 모듈 활성화 설정
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
