name: Xcode - Build and Analyze

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: install CocoaPods Dependency
        run: |
          npm install
          cd ios
          pod install --repo-update
      - name: Start xcode build 🛠
        run: |
          xcodebuild clean test -project ios/DIMI_FRIEND.xcodeproj -scheme DIMI_FRIEND -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4' CODE_SIGNING_ALLOWED=NO