name: iOS Build & Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install NPM Dependencies
        run: |
          npm install

      - name: Install Pod Dependencies
        run: |
          cd ios && pod install --repo-update --clean-install

      - name: Select Xcode 15.3
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.3"

      - name: Build iOS App
        run: |
          cd ios
          xcodebuild clean build -workspace DIMI_FRIEND.xcworkspace \
            -scheme DIMI_FRIEND \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO

      - name: Run iOS Tests
        run: |
          cd ios
          xcodebuild test -workspace DIMI_FRIEND.xcworkspace \
            -scheme DIMI_FRIEND \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.5'
