name: Build and Deploy iOS App

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install JavaScript dependencies
        run: yarn install

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS App Archive
        run: |
          xcodebuild -workspace ios/DIMI_FRIEND.xcworkspace \
                     -scheme DIMI_FRIEND \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath ${{ github.workspace }}/build/DIMI_FRIEND.xcarchive archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath ${{ github.workspace }}/build/DIMI_FRIEND.xcarchive \
                     -exportOptionsPlist ios/exportOptions.plist \
                     -exportPath ${{ github.workspace }}/build

      - name: Run Fastlane for Deployment
        run: |
          cd ios
          fastlane release
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          # 필요에 따라 추가적인 환경변수를 설정하세요.